tap "heroku/brew"
tap "opencode-ai/tap"
tap "sst/tap"
brew "ack"
brew "bash-completion"
brew "blueutil"
brew "brew-cask-completion"
brew "brew-pip"
brew "carthage"
brew "ctags"
brew "docker", link: false
brew "docker-machine"
brew "fzf"
brew "gh"
brew "git"
brew "go"
brew "lsd"
brew "mas"
brew "mysql", restart_service: :changed
brew "mysql@8.4"
brew "neovim"
brew "node"
brew "nvm"
brew "pandoc"
brew "pip-completion"
brew "postgresql@14"
brew "pyenv"
brew "python@3.14"
brew "python@3.9"
brew "reattach-to-user-namespace"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "uv"
brew "vim"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "sst/tap/opencode"
cask "1password-cli"
cask "alfred"
cask "android-file-transfer"
cask "appcleaner"
cask "betterzip"
cask "caffeine"
cask "cheatsheet"
cask "docker-desktop"
cask "doubletwist"
cask "flux-app"
cask "ghostty"
cask "google-chrome"
cask "iterm2"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "sequel-pro"
cask "skim"
cask "sublime-text"
cask "superduper"
cask "suspicious-package"
cask "transmission"
cask "vagrant"
cask "vagrant-manager"
cask "valentina-studio"
cask "virtualbox"
cask "visual-studio-code"
cask "webpquicklook"
cask "xquartz"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "CrystalFetch", id: 6454431289
mas "Dark Reader for Safari", id: 1438243180
mas "Final Cut Pro", id: 424389933
mas "GarageBand", id: 682658836
mas "HP Smart", id: 1474276998
mas "iMovie", id: 408981434
mas "Jump Desktop", id: 524141863
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Notion Web Clipper", id: 1559269364
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Prime Video", id: 545519333
mas "Slack", id: 803453959
mas "Spark Desktop", id: 6445813049
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
vscode "anthropic.claude-code"
vscode "bradymholt.pgformatter"
vscode "codium.codium"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "ecmel.vscode-html-css"
vscode "eighthundreds.notebook"
vscode "esbenp.prettier-vscode"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "james-yu.latex-workshop"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestorage"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.anaconda-extension-pack"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.azure-account"
vscode "ms-vscode.azurecli"
vscode "ms-vscode.cpptools"
vscode "ms-vsliveshare.vsliveshare"
vscode "ms-vsliveshare.vsliveshare-audio"
vscode "ms-vsliveshare.vsliveshare-pack"
vscode "parallelsdesktop.parallels-desktop"
vscode "quicktype.quicktype"
vscode "redhat.java"
vscode "redhat.vscode-commons"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "tobiah.unity-tools"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "visualstudiotoolsforunity.vstuc"
vscode "vscjava.migrate-java-to-azure"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-upgrade"
vscode "vscjava.vscode-maven"
vscode "vscode-icons-team.vscode-icons"
vscode "vscodevim.vim"
vscode "yzane.markdown-pdf"
go "github.com/bootdotdev/bootdev"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
